### ISSUE TITLE
Error while running code 

### ISSUE THREAD

**Issue by Himanshu-Bhalla-2002** [Daltonic/dapplottery#2]
event - compiled client and server successfully in 1025 ms (482 modules)
error - Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
    at Logger.makeError (/Users/himanshubhalla/Desktop/meet/dappLottery/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/Users/himanshubhalla/Desktop/meet/dappLottery/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at JsonRpcProvider.<anonymous> (/Users/himanshubhalla/Desktop/meet/dappLottery/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:609:54)
    at step (/Users/himanshubhalla/Desktop/meet/dappLottery/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/himanshubhalla/Desktop/meet/dappLottery/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/himanshubhalla/Desktop/meet/dappLottery/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork',
  page: '/'
}
wait  - compiling /_error (client and server)...
event - compiled client and server successfully in 226 ms (483 modules)

![image](https://user-images.githubusercontent.com/71603015/235375599-6e4f128b-5a33-4639-bc8e-945fdc4545b6.png)

I am getting the above error.

**Comment by joshuasoftdev** [comment]
you ever fix this issue? i have the same problem

**Comment by adaltonreis** [comment]
Hello everyone! I am having the same issue. Any suggestions?

I appreciate it!

**Comment by AndresFJG** [comment]
To solve this error you must go to the services folder then to the blockchain.srr.js file and in const provider = new ethers.providers.JsonRpcProvider('http://localhost:8545') change the "'http:// localhost : 8545'" for "http://127.0.0.1:8545/" and that's it
